name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0
      with:
          node-version: '18'
        
    - name: Angular Install
      working-directory: ./angular
      run: npm install

    - name: Angular Build
      working-directory: ./angular
      run: npm run build
        
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Copy Secrets
      run: |
        echo "NOW=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        echo ${{ secrets.DEPLOYMENT }} | base64 -d >> deployment.yaml
        sed -i 's/MYSQL_DSN/${{ secrets.MYSQL_DSN }}/g' ./config/config.yaml
        sed -i 's/MSSQL_DSN/${{ secrets.MSSQL_DSN }}/g' ./config/config.yaml
        sed -i 's/ORACLE_DSN/${{ secrets.ORACLE_DSN }}/g' ./config/config.yaml
        sed -i 's/POSTGRESQL_DSN/${{ secrets.POSTGRESQL_DSN }}/g' ./config/config.yaml
        sed -i 's/TAG/$NOW/g' deployment.yaml
        scp -i ${{ secrets.SSH_KEY_BASE64 }} | base64 -d deployment.yaml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WEB_FOLDER }}deployment.yaml
        
    - name: Go Get
      run: go get -v
        
    - name: Go Test
      run: go test -v ./...

    - name: Go Build
      run: go build -o jgo

    - name: Build the Docker image
      run: docker build . --tag ${{ secrets.HARBOR }}/jgo:$NOW

    - name: Login Harbor
      run: docker login -u ${{ secrets.HARBOR_USER }} -p ${{ secrets.HARBOR_PWD }} ${{ secrets.HARBOR_URL }}

    - name: Push Image
      run: docker push ${{ secrets.HARBOR }}/jgo:$NOW

    - name: Start Image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ secrets.WEB_FOLDER }}
          kubectl apply -f deployment.yaml